// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzwwmevztxlbylewcgsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6d3dtZXZ6dHhsYnlsZXdjZ3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTExNjcsImV4cCI6MjA2NjY2NzE2N30.zdMdz9zdncFiasEct7NpMnwb7RawDYeVLW5vMpuaSn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);